### ISSUE TITLE
As a User, I want to report a picture and description

### ISSUE THREAD

**Issue by hubjongit** [hubjongit/soen341app#13]
Users should be able to report a picture or it's description if they feel uncomfortable with its content. These reports are then made available to a dedicated platform administrator so that they can monitor, review, and handle these reports which appropriate action.

Reporting pictures should be anonymous and confidential so that the picture/description poster is not informed and no details are shared. In addition, Users should be able to specify the reason for the report (i.e: spam, inappropriate, hate-speech, etc)

**Comment by DanielWill-Baggs** [comment]
All sub User Stories have been successfully completed and closed, therefore, this Feature can be marked as complete and CLOSED as well.
