### ISSUE TITLE
As a User, I want to report a post directly from it

### ISSUE THREAD

**Issue by hubjongit** [hubjongit/soen341app#14]
**FEATURE: #13** 
Users should be able to access the ability to report a picture or its description from that picture directly. This should likely take form as a button embedded in the picture/description post.

Implementation can be decided, options include:
- Button that redirects to a "report picture/description" page with a form
- Button that displays pop-up with reporting form

Considerations:
- The input fields necessary for completing a report form
- If pop-up, will there be a confirmation, AJAX?
- If a button, ensure that redirection (if applicable, url parameters) are secure and/or validated (only reporting that specific post)

**Acceptance Test:**
- Step 1: Ensure the report does not exceed 200 characters.
- Step 2: Ensure the report is saved.
- Step 3: Ensure the report is linked to the post it refers to.

> RISK: _low_
> PRIORITY: _high_
> POINTS: _7_

**Comment by DanielWill-Baggs** [comment]
All sub Tasks have been successfully completed and closed, therefore, this User Story can be marked as complete and CLOSED as well.
