### ISSUE TITLE
Define Project Naming Conventions and/or Procedures

### ISSUE THREAD

**Issue by hubjongit** [hubjongit/soen341app#17]
Add a Wiki page that defines the discussed and decided naming conventions for:

* branches
* commits
* pull requests
* pull request reviews
* issues (at different levels)

Add any others that were discussed or missed.

**Comment by hubjongit** [comment]
The completed documentation for the adopted project conventions can be found here:
https://github.com/hubjongit/soen341app/wiki/Project-Conventions,-Practices,-&-Procedures

@DanielWill-Baggs Please manually review for any errors and confirm approval. Thank you!

**Comment by DanielWill-Baggs** [comment]
@hubjongit Reviewed and approved. Project Conventions, Practices & Procedures are up to a good standard!
