### ISSUE TITLE
Add Meeting Minutes 2 to GitHub Wiki 

### ISSUE THREAD

**Issue by AhmadHashems** [hubjongit/soen341app#19]
Upload the Meeting Minutes of the second meeting to the soen341app repository's Wiki.

**Comment by hubjongit** [comment]
The Meeting Minutes 2 can be found here:
https://github.com/hubjongit/soen341app/wiki/Meeting-Minutes-%232-(03-01-21)

@AhmadHashems Please manually review them and approve. Thank you.

**Comment by AhmadHashems** [comment]
Thanks for uploading Metting Minutes 2. I reviewed them and they look very good and I approve them. Thank you @hubjongit.
