### ISSUE TITLE
Research the Given Framework Component

### ISSUE THREAD

**Issue by hubjongit** [hubjongit/soen341app#22]
In effort to find a starting point for development, please research the following component respectively as discussed and agreed during Meeting 3.

* @OliverA100 React
* @AhmadHashems MongoDB
* @DanielWill-Baggs React
* @Anusha-Reddy-Lattupally MongoDB
* @hubjongit Django

Research information should include details of the Python implementation of the given component, how to install and set up the package, basic use of that package (tutorials on ORM for MongoDB in Python or tutorials on using React for UI), all so that we can integrate these various components and begin development shortly afterwards.
The team will review the information found during the next meeting.

**Comment by hubjongit** [comment]
So i think we’ve reached a fundamental crossroads. The main advantage and benefit of Django is in fact its built in powerful features such as having an ORM built in (translation: having the database aspect integrated within the backend, unlike flask where u need to import sqlalchemy and make the link yourself) and its Auth (all login/registration stuff is built into DJango and u dont need to import packages like flask-login in Flask) and the Admin page (fun fact Django actually comes with an entire prebuilt backend portal Admin page where u can see all the ex: posts and delete, add more etc). These are literally the reasons why people use Django, cause it saves time and supports these things implicitly. This is VERY important because it means that these features are  1) integrated super well as in literally the Django company makes them, not some independent developer 2) the rest of Django is built to work with them automatically. So yes Django is sick and has all this stuff built into it out of the box and yay. Then we come to MongoDB. Online reviews are mixed but overall we all can agree its gaining big popularity and is good to know. Looking at it on its own, its great, has a nice online interface (unlike MySQL which is legit like tables and spreadsheets), and its pretty easy to read and understand. So whats the problem? The problem is that Django and MongoDB are naturally incompatible.
As I mentioned Django’s great built in DB-support ORM is built on SQL. Its that simple, Django is made by its company to work with SQL naturally. Okay, it is what it is, but If i still wanna use MongoDB, whats the issue? Well the issue is that after doing a lot more research, I see there is no clean solution. First off, PyMongo is out the window simply because not only does it not use Django Models (this is the built in class that if u extend it with any class u create, that class will automatically be created as a table in the MySQL DB), but it doesnt actually even use MongoDB Documents (the MongoDB equivalent of a Model, or SQL table). The code you end up writing is literally raw dict parsing/iteration and u index stuff with very specific strings that need to match the format in the MongoDB Document. Then we get to MongoEngine, which seems much better. It links a Python class with a MongoDB document, and it does this by introducing a new special MongoEngine class called Document that u import from the mongoengine package. This Document class is essentially the same thing as Django Model class. If you want to create a new Document (which, again, is the MongoDB name for a Django Model/SQL Table, but for our case say u want to define a “Post” which would include title, caption, etc), you simply create the class and extend the imported Document from MongoEngine. Then you add fields just like you would in the original Django Model, and now finally we have a solution where we are actually using classes and class instances (objects) to represent data (in our case, we have a Post class with instance variables title, caption, and say we did `Post myPost = new Post("hello", "caption here")`, we can just do `myPost.caption` to get it. This is Java syntax but want u all to get the point) while using MongoDB and NOT some SQL database. Okay, this solution is nice, we have basically reimplemented Django Models with MongoDB Documents by using the MongoEngine package. The problem is obvious when u realize that u just RE-implemented something that was already there in a nearly identical way, and remember how i said django is sick cause of the ORM (built in DB support), Auth, and Admin, and how cause Django supplies them all they also all work with eachother. Well we just took out the ORM puzzle piece and put in MongoEngine piece that looks the same but doesnt actually connect to the others. As a result we would now have to also RE-implement an Auth to handle register and login and sessions. Yes, MongoEngine has its own Auth so u can replace `from django.contrib.auth import User` with `from mongoengine.django.auth import User`, and they both work very similarly. The point is that with MongoEngine you can get all the great built in features of Django by completely ignoring them and replicating them with MongoEngine, which begs the question, okay so why do i even need Django if im not gonna use its features in the way they were meant to be used. That brings us to the last MongoDB implementation option, Djongo. Now this seems to be the best of both worlds, since what it does is translate the normal Django ORM (which works with SQL) to the equivalent commands for MongoDB. So you basically do `from djongo import models` instead of `from django.db import models` and then everything u do is the same as you would for Django Models. The Auth is supposed to work as is, so is the Admin page. It seems good, but my research shows that apparently it isnt 100% stable and you will run into limitations or edge cases where youre stuck.
So all this to say, we have a dilemma and decision to make. We can maximize the number of new frameworks we learn and just throw it all together and not care about the fact that the frameworks contradict each other, and even though now we might know how each works (on some level), our actual example implementation is basically trash (basically a “wrong formula right answer” situation). In that case, whats the point in learning and implementing that framework at all… 90% of Djangos selling point is powerful ORM/Auth/Admin. Well if we arent making use of those, we may as well use Flask with MongoDB. Im starting to realize that any MongoDB implementation in Django is gonna cause us more trouble trying to implement it than actually using those frameworks to support building our core features. However, I know that Ahmad spent a lot of time learning MongoDB and setting it up and writing functions, and I really liked the idea of using it cause its very popular right now. I think ive written enough, and i hope while reading u actually understand the concepts im explaining cause this is basically the top 40 google search results articles combined into one. Personally, and I really hate to say it cause I REALLY wanted to learn MongoDB, but I think knowing Django and the right way to use it will be more valuable than MongoDB. I think more full-stack positions are looking for Django knowledge, and idk i guess im ok with learning MongoDB the next chance I get. Even right now im thinking to myself “is there any way to make both work” but i also think that if i kept the GitHub repo public and a hiring dev saw that I did Django + MongoDB, maybe theyll think i lack a fundamental understanding of what each do and their use cases. Let me know your thoughts.
P.S. Worth mentioning that say we decide that MongoDB is more important to learn and we drop Django, the most logical and popular alternative is using node.js as the backend framework which is actually a javascript framework so youre gonna be also giving up enhancing Python skills, and ur javascript needs to be good. The other option is Flask cause Flask is super simple, but thats if youre okay with another Flask project, thats up to you.

**Comment by AhmadHashems** [comment]
After thorough research, we will shift from using MongoDB to SQLite the original database in Django, which will allow us to use Django built-in functions to handle database requests.  In addition, rest-frame-work will be used with Django to handle requests coming from React frontend.

**Comment by AhmadHashems** [comment]
Note on research completed for React:
Extensive research taught us that React is ideally used as a Single Page Application (SPA) and therefore the traditional idea of the backend (Django) taking care of the URL routing (endpoints) was not applicable anymore. Several options are available to set up the communication between the frontend and the backend:
Creating many react apps and include them with the Django project.
Using Webpack module bundler to bundles React Javascript.
Using React as one app and it handles the routing to all of its pages.

**Comment by hubjongit** [comment]
After trying many different integration options, it was decided that we would use React to develop our frontend and transfer the URL routing to React and react-router (the pkg used for this). In addition, we would need find a way to perform authentication between Django and React for account restricted pages and API endpoints etc.
The React app would be built as an SPA and then served statically through Django and a "catchall" URL config.
Other issues do exist with this option but it seems the most feasible and these errors will be resolved as they are found.
