### ISSUE TITLE
Add Meeting Minutes 5.5 (Scrum) to GitHub Wiki

### ISSUE THREAD

**Issue by hubjongit** [hubjongit/soen341app#43]
Upload the Meeting Minutes of the informal Scrum meeting that took place between meetings 5 and 6, to the soen341app repository's Wiki.

**Comment by OliverA100** [comment]
The Meeting Minutes 5.5 (Scrum) can be found here:
https://github.com/hubjongit/soen341app/wiki/Meeting-Minutes-%235.5-(Scrum)-(21-02-21)

@AhmadHashems Please manually review them and approve. Thank you.

**Comment by AhmadHashems** [comment]
Thanks for adding "Meeting Minutes 5.5 (Scrum)". Approved!
