### ISSUE TITLE
Research Online MySQL DB Hosting Solutions

### ISSUE THREAD

**Issue by hubjongit** [hubjongit/soen341app#66]
Over the course of development we have noticed increasing issues, merge conflicts, and overall difficulties with version controlling our SQLite database. However, having access to the same DB across team members is important for testing and Django's migrations commands for table.

Therefore, research options of hosting a MySQL database on an online server (one option seems to be Google Cloud SQL)

**Comment by AhmadHashems** [comment]
I found a way to host our database online. Our database will be "postgresql" and hosted on "elephantsql", so every team member can add the credentials of the online database in the settings.py file.
