### ISSUE TITLE
Add block diagram to GitHub Wiki

### ISSUE THREAD

**Issue by AhmadHashems** [hubjongit/soen341app#97]
Upload a block diagram that is consistent with the code to the soen341app repository's Wiki.

**Comment by AhmadHashems** [comment]
The block diagram can be found here:
https://github.com/hubjongit/soen341app/wiki/Project-Architecture

@OliverA100 please review the block diagram.

**Comment by OliverA100** [comment]
The block diagram looks good! It follows the same structure shown during SOEN 341 lectures. Thank you for making it.
